# fly.toml app configuration file generated for eugene-server-3 on 2025-06-18T12:41:30+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "eugene-server-3"
primary_region = "otp"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
